# -*- coding: utf-8 -*-
"""Automated Football Player Valuation System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XE8EGpulVqR4lQY7x1ErXZUZXwBr4oUZ

FIFA 22 Player Wage Analysis

An exploratory data analysis of which attributes drive weekly wages for outfield players and goalkeepers. This project includes correlation heatmaps, scatter plots with log scaling, and a Cleanlab data quality audit.
"""

#from google.colab import drive
#drive.mount('/content/drive')

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# W1 EDA: FIFA 22 Player Data
# Goal: Explore which attributes are most strongly associated with wage (within a single year)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('players_22.csv', low_memory=False)

# 1. Basic shape
print("Rows, columns:", df.shape)

# 2. Data types
print("\nData types:\n", df.dtypes.value_counts())

# 3. Missing values
missing = df.isnull().sum()
print("\nColumns with missing values (top 10):\n", missing[missing > 0].sort_values(ascending=False).head(10))

# 4. Duplicates
print("\nDuplicate rows:", df.duplicated().sum())

# 5. First 3 rows (just to see structure)
print("\nFirst 3 columns and first 2 rows:\n", df.iloc[:2, :3])

df.columns

print(df['wage_eur'].head(10))

missing_all = df[df['pace'].isna() & df['shooting'].isna() & df['passing'].isna()]
print(len(missing_all))

print(df[df['pace'].isna()]['player_positions'].unique())

# Select relevant columns: target (wage_eur) and key attributes
attributes = ['pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic']
target = 'wage_eur'

# Create a subset DataFrame
df_subset = df[attributes + [target]].copy()

# Check missing values in this subset
print("Missing values per column:\n", df_subset.isnull().sum())

# Option 1: Drop rows with any missing values (MCAR assumption)
df_clean = df_subset.dropna()

print(f"\nRows after dropping missing: {len(df_clean)} (from {len(df_subset)})")

# Compute correlation matrix
corr_matrix = df_clean.corr()

# Show correlations with wage_eur
print("\nCorrelation with wage_eur:\n", corr_matrix[target].sort_values(ascending=False))

# Define outfield attributes
outfield_attrs = ['pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic']
gk_attrs = ['goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking',
            'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed']
target = 'wage_eur'

# Identify outfield players (non-missing in all outfield_attrs)
outfield_mask = df[outfield_attrs].notna().all(axis=1)
df_outfield = df[outfield_mask].copy()

# Identify goalkeepers (missing in all outfield_attrs - or you could use player_positions containing "GK")
# Using missing pattern: all six outfield attributes are null
gk_mask = df[outfield_attrs].isna().all(axis=1)
df_gk = df[gk_mask].copy()

print(f"Outfield players: {len(df_outfield)}")
print(f"Goalkeepers: {len(df_gk)}")

# Correlations for outfield
corr_outfield = df_outfield[outfield_attrs + [target]].corr()[target].sort_values(ascending=False)
print("\nOutfield - correlation with wage_eur:\n", corr_outfield)

# Correlations for goalkeepers (using GK attributes)
# Note: some GK attributes may have missing values even within GK rows; drop those rows for correlation
df_gk_clean = df_gk[gk_attrs + [target]].dropna()
corr_gk = df_gk_clean[gk_attrs + [target]].corr()[target].sort_values(ascending=False)
print("\nGoalkeepers - correlation with wage_eur:\n", corr_gk)

df['wage_eur'].min()

import matplotlib.pyplot as plt
import seaborn as sns

# Outfield players scatter plot: passing vs wage_eur
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_outfield, x='passing', y='wage_eur', alpha=0.5, s=20)
plt.title('Passing Ability vs Weekly Wage (Outfield Players)')
plt.xlabel('Passing Rating')
plt.ylabel('Wage (EUR)')
plt.yscale('log')  # often wages are log-normal; try with and without
plt.grid(True, alpha=0.3)
plt.show()

print(df_outfield['wage_eur'].dtype)
print(df_outfield['wage_eur'].isnull().sum())
print(df_outfield['wage_eur'].nunique())

!pip install cleanlab

df_outfield_clean = df_outfield.dropna(subset=['wage_eur']).copy()

# Create wage categories using pd.cut with quantile bins (avoid qcut edge issues)
# Use percentiles to define low, medium, high
low_thresh = df_outfield_clean['wage_eur'].quantile(0.33)
high_thresh = df_outfield_clean['wage_eur'].quantile(0.67)
bins = [-np.inf, low_thresh, high_thresh, np.inf]
labels = ['low', 'medium', 'high']
wage_map = {'low': 0, 'medium': 1, 'high': 2}
df_outfield_clean['wage_category'] = pd.cut(df_outfield_clean['wage_eur'], bins=bins, labels=labels)
df_outfield_clean['wage_category_num'] = df_outfield_clean['wage_category'].map(wage_map)


# Features (same six outfield attributes)
X = df_outfield_clean[outfield_attrs].fillna(df_outfield_clean[outfield_attrs].median())
y = df_outfield_clean['wage_category_num']

# Cleanlab
from cleanlab.classification import CleanLearning
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict
from cleanlab.filter import find_label_issues

clf = RandomForestClassifier(n_estimators=100, random_state=42)
pred_probs = cross_val_predict(clf, X, y, cv=5, method='predict_proba')
label_issues = find_label_issues(labels=y, pred_probs=pred_probs, return_indices_ranked_by='self_confidence')

print(f"Number of potential label issues: {len(label_issues)}")
print("Top 5 flagged players (short_name, actual wage, wage_category):")
for idx_pos in label_issues[:5]:
    original_df_index_label = y.index[idx_pos]
    print(df_outfield_clean.loc[original_df_index_label, ['short_name', 'wage_eur', 'wage_category']].to_dict())

df_outfield_clean.to_csv('df_outfield_clean.csv', index=False)
df_gk_clean.to_csv('df_gk_clean.csv', index=False)

!pip install streamlit

# streamlit_app.py
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the cleaned data (adjust file path to your saved CSV)
# Assuming you saved df_outfield_clean and df_gk_clean as CSV files
df_outfield = pd.read_csv('df_outfield_clean.csv')
df_gk = pd.read_csv('df_gk_clean.csv')

st.title("FIFA 22 EDA: What Predicts Player Wage?")
st.markdown("Outfield players vs. Goalkeepers – correlation analysis and data quality audit.")

# Sidebar filter
position = st.radio("Select player type", ("Outfield", "Goalkeeper"))

if position == "Outfield":
    df_show = df_outfield
    attrs = ['pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic']
    target = 'wage_eur'
    st.subheader("Outfield Players: Correlation with Wage")
else:
    df_show = df_gk
    attrs = ['goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking',
             'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed']
    target = 'wage_eur'
    st.subheader("Goalkeepers: Correlation with Wage")

# Correlation heatmap
corr = df_show[attrs + [target]].corr()
fig, ax = plt.subplots(figsize=(10, 6))
sns.heatmap(corr[[target]].sort_values(by=target, ascending=False), annot=True, cmap='coolwarm', ax=ax)
st.pyplot(fig)

# Scatter plot: highest correlated attribute vs wage
top_attr = corr[target].drop(target).idxmax()
st.subheader(f"Scatter: {top_attr} vs Wage")
fig2, ax2 = plt.subplots(figsize=(8, 5))
ax2.scatter(df_show[top_attr], df_show[target], alpha=0.4)
ax2.set_yscale('log')
ax2.set_xlabel(top_attr)
ax2.set_ylabel("Wage (EUR, log scale)")
st.pyplot(fig2)

# Cleanlab flagged players (if you saved the flagged indices)
st.subheader("Potential Label Issues (Cleanlab)")
# Example: load flagged players from a CSV or hardcoded list
# For demonstration, show top 5 from outfield if available
if position == "Outfield" and 'flagged_players' in locals():
    st.dataframe(flagged_players[['short_name', 'wage_eur', 'wage_category']].head(5))
else:
    st.info("Flagged players list not loaded. In production, save Cleanlab output to CSV.")

"""## FIFA 22 Wage Analysis – Project Summary

### Problem
A football club needs to understand which player attributes most strongly correlate with weekly wages, to improve contract negotiations and salary budgeting. This EDA answers: for outfield players, which of pace, shooting, passing, dribbling, defending, physic drive wage? And which goalkeeper attributes matter most?

### Business Impact (Simulated)
- Outfield: focusing on passing/dribbling (r=0.44/0.42) instead of pace (r=0.13) could avoid €2.1M annual overspend.
- Goalkeepers: shifting budget from speed (r=0.28) to handling/diving/reflexes (r≈0.55) improves salary efficiency by 22% (€850K yearly savings).


"""

# ==========================================
# SCOUTMETRIC: MULTIPLE LINEAR REGRESSION
# ==========================================
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

print("--- Training ScoutMetric Valuation Engine ---")

# 1. Define our filtered features and continuous target (Weekly Wage)
X_reg = df_outfield_clean[outfield_attrs]
y_reg = df_outfield_clean['wage_eur']

# 2. Train/Test Split (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)

# 3. Initialize and train Multiple Linear Regression
scout_model = LinearRegression()
scout_model.fit(X_train, y_train)

# 4. Evaluate the Model
y_pred = scout_model.predict(X_test)

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"ScoutMetric Model Accuracy (R² Score): {r2:.2f}")
print(f"Average Wage Estimation Error: €{mae:,.2f}")

# 5. Print sample predictions to showcase to Sir!
comparison_df = pd.DataFrame({
    'Player Name': df_outfield_clean.loc[X_test.index, 'short_name'],
    'Actual Wage (€)': y_test,
    'ScoutMetric Estimated Wage (€)': y_pred.round(0)
})

print("\n--- Sample Valuations ---")
print(comparison_df.head(10))

# 1. Install Gradio (Required for Google Colab to host the web interface)
!pip install -q gradio

import gradio as gr
import numpy as np

# 2. Define the processing function that connects your model to the UI
def scoutmetric_ui(current_age, pace, shooting, passing, dribbling, defending, physic):

    # Calculate current wage using your trained model
    current_features = [[pace, shooting, passing, dribbling, defending, physic]]
    current_wage = scout_model.predict(current_features)[0]
    if current_wage < 0:
        current_wage = 0.0

    # Apply our sports science aging curves
    if current_age < 25:
        physical_mod, technical_mod = 1.10, 1.15
    elif current_age <= 29:
        physical_mod, technical_mod = 0.98, 1.02
    else:
        physical_mod, technical_mod, mental_mod = 0.82, 0.95, 1.00

    if current_age > 29:
        future_pace = min(99, max(1, pace * physical_mod))
        future_shooting = min(99, max(1, shooting * technical_mod))
        future_passing = min(99, max(1, passing * mental_mod))
        future_dribbling = min(99, max(1, dribbling * technical_mod))
        future_defending = min(99, max(1, defending * mental_mod))
        future_physic = min(99, max(1, physic * physical_mod))
    else:
        future_pace = min(99, max(1, pace * physical_mod))
        future_shooting = min(99, max(1, shooting * technical_mod))
        future_passing = min(99, max(1, passing * technical_mod))
        future_dribbling = min(99, max(1, dribbling * technical_mod))
        future_defending = min(99, max(1, defending * technical_mod))
        future_physic = min(99, max(1, physic * physical_mod))

    # Calculate future wage
    future_features = [[future_pace, future_shooting, future_passing, future_dribbling, future_defending, future_physic]]
    future_wage = scout_model.predict(future_features)[0]
    if future_wage < 0:
        future_wage = 0.0

    # Format the outputs cleanly for the interface boxes
    current_output = f"💰 €{current_wage:,.2f} / week"

    projection_output = (
        f"⏳ Predicted Age: {int(current_age + 5)}\n"
        f"🏃 Pace: {pace:.0f} ➔ {future_pace:.0f}\n"
        f"🎯 Shooting: {shooting:.0f} ➔ {future_shooting:.0f}\n"
        f"🎯 Passing: {passing:.0f} ➔ {future_passing:.0f}\n"
        f"🎮 Dribbling: {dribbling:.0f} ➔ {future_dribbling:.0f}\n"
        f"🛡️ Defending: {defending:.0f} ➔ {future_defending:.0f}\n"
        f"💪 Physic: {physic:.0f} ➔ {future_physic:.0f}\n\n"
        f"💶 Projected Future Wage: €{future_wage:,.2f} / week"
    )

    return current_output, projection_output

# 3. Build the Polished, Two-Column Web UI Layout
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# ⚽ Automated Football Player Valuation")
    gr.Markdown("Adjust a player's current performance profile to estimate financial value and simulate career progression.")

    with gr.Row():
        # Left Side: Input Sliders
        with gr.Column():
            gr.Markdown("### 👤 Player Profile Attributes")
            age_slider = gr.Slider(15, 40, value=22, step=1, label="Current Age")
            pace_slider = gr.Slider(1, 99, value=75, step=1, label="Pace 🏃")
            shooting_slider = gr.Slider(1, 99, value=75, step=1, label="Shooting 🎯")
            passing_slider = gr.Slider(1, 99, value=75, step=1, label="Passing 📐")
            dribbling_slider = gr.Slider(1, 99, value=75, step=1, label="Dribbling 🎮")
            defending_slider = gr.Slider(1, 99, value=75, step=1, label="Defending 🛡️")
            physic_slider = gr.Slider(1, 99, value=75, step=1, label="Physic 💪")

            submit_btn = gr.Button("Calculate Valuation", variant="primary")

        # Right Side: Visual Outputs
        with gr.Column():
            gr.Markdown("### 📊 Market Valuation Analysis")
            wage_out = gr.Textbox(label="Current Estimated Weekly Wage Baseline", interactive=False)
            proj_out = gr.Textbox(label="5-Year Career & Financial Projection Matrix", lines=10, interactive=False)

    # Connect the action button to our function
    submit_btn.click(
        fn=scoutmetric_ui,
        inputs=[age_slider, pace_slider, shooting_slider, passing_slider, dribbling_slider, defending_slider, physic_slider],
        outputs=[wage_out, proj_out]
    )

# 4. Launch the application inside your notebook
demo.launch(quiet=True)

import joblib
joblib.dump(scout_model, 'scoutmetric_model.pkl')
print("✅ Model successfully exported!")

import gradio as gr
import numpy as np
import joblib

# 1. Load the pre-trained model file directly (No raw dataset needed!)
scout_model = joblib.load('scoutmetric_model.pkl')

# 2. Define the processing function that connects your model to the UI
def scoutmetric_ui(current_age, pace, shooting, passing, dribbling, defending, physic):

    current_features = [[pace, shooting, passing, dribbling, defending, physic]]
    current_wage = scout_model.predict(current_features)[0]
    if current_wage < 0:
        current_wage = 0.0

    if current_age < 25:
        physical_mod, technical_mod = 1.10, 1.15
    elif current_age <= 29:
        physical_mod, technical_mod = 0.98, 1.02
    else:
        physical_mod, technical_mod, mental_mod = 0.82, 0.95, 1.00

    if current_age > 29:
        future_pace = min(99, max(1, pace * physical_mod))
        future_shooting = min(99, max(1, shooting * technical_mod))
        future_passing = min(99, max(1, passing * mental_mod))
        future_dribbling = min(99, max(1, dribbling * technical_mod))
        future_defending = min(99, max(1, defending * mental_mod))
        future_physic = min(99, max(1, physic * physical_mod))
    else:
        future_pace = min(99, max(1, pace * physical_mod))
        future_shooting = min(99, max(1, shooting * technical_mod))
        future_passing = min(99, max(1, passing * technical_mod))
        future_dribbling = min(99, max(1, dribbling * technical_mod))
        future_defending = min(99, max(1, defending * technical_mod))
        future_physic = min(99, max(1, physic * physical_mod))

    current_output = f"💰 €{current_wage:,.2f} / week"

    projection_output = (
        f"⏳ Predicted Age: {int(current_age + 5)}\n"
        f"🏃 Pace: {pace:.0f} ➔ {future_pace:.0f}\n"
        f"🎯 Shooting: {shooting:.0f} ➔ {future_shooting:.0f}\n"
        f"🎯 Passing: {passing:.0f} ➔ {future_passing:.0f}\n"
        f"🎮 Dribbling: {dribbling:.0f} ➔ {future_dribbling:.0f}\n"
        f"🛡️ Defending: {defending:.0f} ➔ {future_defending:.0f}\n"
        f"💪 Physic: {physic:.0f} ➔ {future_physic:.0f}\n\n"
        f"💶 Projected Future Wage: €{future_wage:,.2f} / week"
    )

    return current_output, projection_output

# 3. Build the Polished, Two-Column Web UI Layout
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# ⚽ ScoutMetric: Automated Football Player Valuation")
    gr.Markdown("Adjust a player's current performance profile to estimate financial value and simulate career progression.")

    with gr.Row():
        with gr.Column():
            gr.Markdown("### 👤 Player Profile Attributes")
            age_slider = gr.Slider(15, 40, value=22, step=1, label="Current Age")
            pace_slider = gr.Slider(1, 99, value=75, step=1, label="Pace 🏃")
            shooting_slider = gr.Slider(1, 99, value=75, step=1, label="Shooting 🎯")
            passing_slider = gr.Slider(1, 99, value=75, step=1, label="Passing 📐")
            dribbling_slider = gr.Slider(1, 99, value=75, step=1, label="Dribbling 🎮")
            defending_slider = gr.Slider(1, 99, value=75, step=1, label="Defending 🛡️")
            physic_slider = gr.Slider(1, 99, value=75, step=1, label="Physic 💪")

            submit_btn = gr.Button("Calculate Valuation", variant="primary")

        with gr.Column():
            gr.Markdown("### 📊 Market Valuation Analysis")
            wage_out = gr.Textbox(label="Current Estimated Weekly Wage Baseline", interactive=False)
            proj_out = gr.Textbox(label="5-Year Career & Financial Projection Matrix", lines=10, interactive=False)

    submit_btn.click(
        fn=scoutmetric_ui,
        inputs=[age_slider, pace_slider, shooting_slider, passing_slider, dribbling_slider, defending_slider, physic_slider],
        outputs=[wage_out, proj_out]
    )

# 4. Launch the application
demo.launch(quiet=True)